---
name: ToolSet
version: 0.14
author:
  - 'David Golden <dagolden@cpan.org>'
abstract: Load your commonly-used modules in a single import
license: apache
resources:
  license: http://apache.org/licenses/LICENSE-2.0
requires:
  Carp: 0
  base: 0
  perl: 5.006
build_requires:
  Exporter: 0
  Test::More: 0.47
provides:
  ToolSet:
    file: lib/ToolSet.pm
    version: 0.14
  ToolSet::SWC:
    file: lib/ToolSet/SWC.pm
    version: 0.14
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
    - t
